GPU-1078
gentics/cms-oss pull request #128
Opened 2023-08-21 14:34 UTC by guggi

2023-09-01 08:32 UTC, npomaroli requested changes
Please also do not forget to do final cleanup:
Add Javadoc to (at least) all new public classes and methods
Remove unused imports
Check code formatting (tabs instead of spaces, ...)

2023-09-01 08:32 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +  private static boolean checkOtherPackages(
As far as I understand, this methods compares dependencies with each other.
But when checking a package for completeness, we want to know whether a dependency, that is missing in the checked package is CONTAINED in any of the other packages, not whether it is a DEPENDENCY of any other package.

2023-09-01 08:32 UTC, npomaroli commented on cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/devtools/PackageResource.java
> +	GenericResponse performPackageConsistencyCheck(@PathParam("name") String name,
Should return PackageDependencyList (like the implementation does)

2023-09-01 08:32 UTC, npomaroli commented on cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/devtools/PackageResource.java
> +	 * @return list of dependencies and sub dependencies
Is it true, that there are sub dependencies?
If yes, do we need them, or isn't it sufficient to check for direct dependencies only?

2023-09-01 08:32 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
> +  static public String resolveUuid(int datasourceId) throws NodeException {
This is already implemented in com.gentics.contentnode.factory.Transaction.getGlobalId(Class<T>, Integer), with the only difference that you will get null instead of empty string, if the object is not found.

2023-09-01 08:32 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
>            .withName(part.getName().toString())
The dependency is the datasource and not the part, so it should contain the datasource global ID and name

2023-09-01 08:32 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ObjectPropertyResolver.java
> +          .withGlobalId(tag.getGlobalId().toString())
The dependency is the construct, so we should have the globalId and name of the construct, not the tag.

2023-09-01 08:32 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +          .withGlobalId(tag.getGlobalId() != null ? tag.getGlobalId().toString() : "")
Name and globalId should be from the dependency (construct or object property definition), not from the tag.

2023-09-05 13:49 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/PackageResourceImpl.java
> +		if (filter != null && filter.query != null) {
fixed in: 774687e9ad   
the disadvantage of this is that if the filter is wrong, merely a 404 is returned and its hard for a user to know that the filter is wrong. also, this is per default case-sensitive (without overwriting the `fromString` method in the respective ENUMs

2023-09-05 13:50 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
> +  static public String resolveUuid(int datasourceId) throws NodeException {
thx, adjusted in: 774687e9ad

2023-09-05 13:50 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
>            .withName(part.getName().toString())
774687e9ad

2023-09-05 13:50 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ObjectPropertyResolver.java
> +          .withGlobalId(tag.getGlobalId().toString())
774687e9ad

2023-09-05 13:50 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +          .withGlobalId(tag.getGlobalId() != null ? tag.getGlobalId().toString() : "")
774687e9ad

2023-09-05 13:53 UTC, guggi commented on cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/devtools/PackageResource.java
> +	 * @return list of dependencies and sub dependencies
A referenced dependency of a package object was meant by this. 774687e9ad removed it since it causes confusion.

2023-09-05 13:54 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ObjectPropertyResolver.java
> +      List<PackageDependency> references = resolveReferences(objectTagDefinition.getObjectTags());
thx for the clarification!  774687e9ad6

2023-09-05 13:55 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ObjectPropertyResolver.java
> +      if (!UUID_REGEX.matcher(constructId).matches()) {
As discussed in person, this was used to filter out the default constructs with an old uuid and was wrong. removed both regex checks https://github.com/gentics/cms-oss/commit/774687e9ad6ae190e1f19c011c3985e59f5daf01

2023-09-05 13:56 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/exception/InvalidRequestException.java
> +  /**
i hate this, i fixed my setting in my IDE and hope this won’t happen again :see_no_evil:  
https://github.com/gentics/cms-oss/commit/774687e9ad6ae190e1f19c011c3985e59f5daf01

2023-09-06 06:22 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/PackageResourceImpl.java
> +				.page(paging)
774687e9ad: adds sorting by type

2023-09-06 06:24 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
> +									Part.URLPAGE, Part.HTMLLONG, Part.CHECKBOX, Part.VELOCITY),
i am listing the DefaultElement here. is this fine? or should i just exclude the select part types and accept all values?

2023-09-06 06:24 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +      // exclude default constructs
774687e9ad removes it

2023-09-06 06:25 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +  private static List<Future<List<PackageDependency>>> dependencyCheckerTasks;
thx! 774687e9ad 
can many request to this endpoint also be problematic as many threadpools will be created?

2023-09-06 06:26 UTC, guggi commented on cms-restapi/src/main/java/com/gentics/contentnode/rest/resource/devtools/PackageResource.java
> +	GenericResponse performPackageConsistencyCheck(@PathParam("name") String name,
774687e9ad

2023-09-06 06:30 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +  private static boolean checkOtherPackages(
yes, and the synchronizer will take care of the actual check (`AbstractDependencyChecker.isInPackage`) which will set the two flags `isInPackage` and `isInOtherPackage`

2023-09-06 07:38 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +      // exclude default constructs
Also remove the comment "exclude default constructs"

2023-09-06 07:39 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +	private final ExecutorService executor = Executors.newFixedThreadPool(5);
make static

2023-09-06 07:44 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +  private static List<Future<List<PackageDependency>>> dependencyCheckerTasks;
Yes, we could use a static thread pool, or re-use the executor returned by com.gentics.contentnode.rest.util.Operator.getExecutor(). This has the advantage that shutdown is properly handled.

2023-09-06 08:39 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +  private static boolean checkOtherPackages(
Simplfy comparison by getting contained objects from the other packages, not dependencies

2023-09-06 08:42 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
>            .withType(getSynchronizationType(tag))
Actually, I would suggest to separate com.gentics.contentnode.rest.resource.impl.devtools.resolver.TemplateResolver.resolveTags(List<T>) into two methods, one for TemplateTags, one for ObjectTags.

2023-09-06 09:12 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ObjectPropertyResolver.java
> +          .withGlobalId(tag.getGlobalId().toString())
The name is still set to the object property name, not the construct name

2023-09-06 09:14 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
> +									Part.URLPAGE, Part.HTMLLONG, Part.CHECKBOX, Part.VELOCITY),
As discussed, we only need to consider selectsingle and selectmultiple

2023-09-07 11:58 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ObjectPropertyResolver.java
> +          .withGlobalId(tag.getGlobalId().toString())
9de83d896caefb9b9

2023-09-07 11:58 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +      // exclude default constructs
9de83d896caefb9b9

2023-09-07 11:59 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
>            .withType(getSynchronizationType(tag))
9de83d896caefb9b9

2023-09-07 12:03 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/ConstructResolver.java
> +									Part.URLPAGE, Part.HTMLLONG, Part.CHECKBOX, Part.VELOCITY),
removed it!

2023-09-20 11:39 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +					.build().withIsInOtherPackage(
change to .isInPackage()

2023-09-20 11:47 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +			searchReference.withIsInPackage(isInOtherPkg);
use .withisInOtherPackage()

2023-09-20 13:28 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/ConcurrentPackageDependencyChecker.java
> +			searchReference.withIsInPackage(isInOtherPkg);
A: 60bf5e55
B: f335e9eb

2023-09-20 13:28 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/rest/resource/impl/devtools/resolver/TemplateResolver.java
> +					.build().withIsInOtherPackage(
60bf5e55

2023-09-20 14:02 UTC, merged