Hotfix 6.0.x sup 15720
gentics/cms-oss pull request #134
Opened 2023-09-04 14:40 UTC by bogdandavydov

2023-09-04 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gentics/cms-oss?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gentics/cms-oss?pullRequest=134) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: yrucrem<br/>:white_check_mark: deckdom<br/>:x: GenticsDev<br/>:x: Bogdan Davydov<br/><hr/>**Bogdan Davydov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gentics/cms-oss?pullRequest=134) it.</sub>

2023-09-04 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gentics/cms-oss?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gentics/cms-oss?pullRequest=134) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: yrucrem<br/>:white_check_mark: deckdom<br/>:x: GenticsDev<br/>:x: Bogdan Davydov<br/><hr/>**Bogdan Davydov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gentics/cms-oss?pullRequest=134) it.</sub>

2023-09-04 14:50 UTC, npomaroli commented
The Merge Request needs to be directed to branch hotfix-6.0.x, not master.

2023-09-04 14:57 UTC, npomaroli requested changes
Please add a changelog entry explaining the change (to our customers).

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/template.object.bladeTemplateName/gentics_structure.json
> +  "keyword" : "object.bladeTemplateName",
Whats the difference between this object property and the already existing object.templateName?

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/image.object.alt/gentics_structure.json
> +    "en" : "Alternativtext"
Translate to english

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/image.object.alt/gentics_structure.json
> +    "de" : "",
Add descriptions in english and german

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/image.object.alt/gentics_structure.json
> +}
Object Properties from the DefaultElements package must have the category "Gentics CMP Default"

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/template.object.bladeTemplateName/gentics_structure.json
> +    "de" : "Blade Template Name",
Translate to german

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/template.object.bladeTemplateName/gentics_structure.json
> +    "de" : "name of the blade template",
Translate to german

2023-09-04 14:57 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/template.object.bladeTemplateName/gentics_structure.json
> +}
Object Properties from the DefaultElements package must have the category "Gentics CMP Default"

2023-09-04 15:20 UTC, bogdandavydov commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/template.object.bladeTemplateName/gentics_structure.json
> +  "keyword" : "object.bladeTemplateName",
Was soll in object.templateName drinstehen? Der CMS-Template-Name oder der Name der Blade View?

Mehrere CMS-Templates können auf die gleiche Blade-View zeigen, aber sie können nicht gleich benannt sein im CMS.

 
object.templateName = CMS-Templatename

object.bladeTemplateName = Name der Blade View.

2023-09-04 15:31 UTC, bogdandavydov commented
I fixed the problems, pls review

2023-09-05 07:21 UTC, npomaroli requested changes
There is still no changelog entry.

2023-09-05 07:21 UTC, npomaroli commented on cms-core/src/main/resources/packages/DefaultElements/objectproperties/template.object.bladeTemplateName/gentics_structure.json
> +  "keyword" : "object.bladeTemplateName",
object.templateName is meant to contain the template name in the portal (regardless of whether it is a blade view in portal | php or a handlebars template in portal | java). There is no need to have an object property containing the CMS template name, because the template has a "name" property.
So this object property object.bladeTemplateName is superfluous and its name (blade...) also hints to a specific portal version, which we don't want to have in the default elements.

2023-09-06 07:56 UTC, bogdandavydov commented
@npomaroli, i deleted bladeTemplateName property, we really don't need it.

2024-03-25 09:24 UTC, bogdandavydov commented
Added changelog entry

2026-07-06 09:58 UTC, closed without merging