Hotfix 6.0.x sup 16004
gentics/cms-oss pull request #230
Opened 2024-03-21 10:32 UTC by plyhun

2024-03-21 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gentics/cms-oss?pullRequest=230) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gentics/cms-oss?pullRequest=230) before we can accept your contribution.<br/><hr/>**Serhii Plyhun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gentics/cms-oss?pullRequest=230) it.</sub>

2024-03-21 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gentics/cms-oss?pullRequest=230) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gentics/cms-oss?pullRequest=230) before we can accept your contribution.<br/><hr/>**Serhii Plyhun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gentics/cms-oss?pullRequest=230) it.</sub>

2024-03-21 10:36 UTC, plyhun commented on cms-oss-server/src/main/java/com/gentics/contentnode/servlets/SelectedSymlinkAllowedResourceAliasChecker.java
> +public class SelectedSymlinkAllowedResourceAliasChecker extends AllowedResourceAliasChecker
Here we cannot reuse an existing `SymlinkAllowedResourceAliasChecker` for two reasons.
1. It is enabled by default, thus - useless.
2. It is useless, because of its ultimate dependency on a base webroot, which is set to `/webroot`, which is based on an application classpath root, and not the root we set in the distinct handler.

2024-03-22 10:56 UTC, npomaroli requested changes
Tested with the example setup of the ticket and it did not work (static file from symlinked package is not availalbe).

2024-03-22 16:52 UTC, plyhun commented
> Tested with the example setup of the ticket and it did not work (static file from symlinked package is not availalbe).

I was able to replicate the issue on a local setup. Will re-check with the provided docker environment as well.

2024-03-25 13:37 UTC, plyhun commented on cms-oss-server/src/main/java/com/gentics/contentnode/servlets/SelectedSymlinkAllowedResourceAliasChecker.java
> +public class SelectedSymlinkAllowedResourceAliasChecker extends AllowedResourceAliasChecker
NB: Fresher Jetty version extends the possibility of AliasCheckers, though it requires a refactoring / overall stability check.
https://github.com/jetty/jetty.project/issues/8259

2024-03-26 13:06 UTC, npomaroli approved these changes

2024-03-26 13:07 UTC, merged