WIP: SUP-16409: Move objects between nodes + Mesh Publish (UT)
gentics/cms-oss pull request #245
Opened 2024-04-02 14:26 UTC by plyhun

2024-04-02 14:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gentics/cms-oss?pullRequest=245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gentics/cms-oss?pullRequest=245) before we can accept your contribution.<br/><hr/>**Serhii Plyhun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gentics/cms-oss?pullRequest=245) it.</sub>

2024-04-02 14:27 UTC, plyhun commented on cms-core/src/test/java/com/gentics/contentnode/tests/publish/mesh/MeshPublishTest.java
> +			context.publish(false);
Crash here.

2024-04-02 14:27 UTC, plyhun commented on cms-core/src/test/java/com/gentics/contentnode/tests/publish/mesh/MeshPublishTest.java
> +			context.publish(false);
```
14:27:31.558 [] ERROR [vert.x-worker-thread-17] [c.g.m.g.OrientDBDatabase] - com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #1122:5: found duplicated key 'a7e7596bf0f911ee96030242ac120002' in index 'MeshVertexImpl' previously assigned to the record #1121:5
	DB name="tinkerpop1712066498378" INDEX=MeshVertexImpl RID=#1121:5
14:27:31.558 [] ERROR [vert.x-eventloop-thread-13] [c.g.m.r.r.FailureHandler] - Error for request in path: /api/v1/othertestproject/nodes/a7e7596bf0f911ee96030242ac120002?branch=othertestproject&etag=false&fields=uuid,parent
14:27:31.558 [] ERROR [vert.x-eventloop-thread-13] [c.g.m.r.r.FailureHandler] - Error:
com.gentics.mesh.core.rest.error.GenericRestException: 500 Internal Server Error error_internal params {}
	at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:90)
	at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:535)
	at com.gentics.mesh.core.verticle.handler.HandlerUtilities.syncTx(HandlerUtilities.java:345)
	at com.gentics.mesh.core.verticle.handler.HandlerUtilities.createOrUpdateElement(HandlerUtilities.java:189)
	at com.gentics.mesh.core.verticle.handler.HandlerUtilities.createOrUpdateElement(HandlerUtilities.java:172)
	at com.gentics.mesh.core.verticle.handler.HandlerUtilities.updateElement(HandlerUtilities.java:153)
	at com.gentics.mesh.core.endpoint.handler.AbstractCrudHandler.handleUpdate(AbstractCrudHandler.java:89)
	at com.gentics.mesh.core.endpoint.node.NodeEndpoint.lambda$addUpdateHandler$20(NodeEndpoint.java:524)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
14:27:31.559 [] ERROR [vert.x-eventloop-thread-13] [i.v.e.w.h.i.LoggerHandlerImpl] - 172.17.0.1 - POST /api/v1/othertestproject/nodes/a7e7596bf0f911ee96030242ac120002?branch=othertestproject&etag=false&fields=uuid,parent HTTP/1.1 500 178 - 8 ms

Mesh output for failed test testUnrecoverableFilenameConflict(com.gentics.contentnode.tests.publish.mesh.MeshPublishTest)
```

2024-04-02 14:29 UTC, plyhun commented on cms-core/src/test/java/com/gentics/contentnode/tests/publish/mesh/MeshPublishTest.java
> +			context.publish(false);
A line earlier
```
14:27:31.515 [] WARN  [vert.x-eventloop-thread-13] [i.v.e.w.h.i.LoggerHandlerImpl] - 172.17.0.1 - DELETE /api/v1/testproject/nodes/a7e7596bf0f911ee96030242ac120002/languages/de?recursive=true HTTP/1.1 404 220 - 2 ms
14:27:31.558 [] ERROR [vert.x-worker-thread-17] [c.g.m.g.OrientDBDatabase] - com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #1122:5: found duplicated key 'a7e7596bf0f911ee96030242ac120002' in index 'MeshVertexImpl' previously assigned to the record #1121:5
	DB name="tinkerpop1712066498378" INDEX=MeshVertexImpl RID=#1121:5
14:27:31.558 [] ERROR [vert.x-eventloop-thread-13] [c.g.m.r.r.FailureHandler] - Error for request in path: /api/v1/othertestproject/nodes/a7e7596bf0f911ee96030242ac120002?branch=othertestproject&etag=false&fields=uuid,parent
```
shows that an attempt to delete an old node is performed, with no success.

2024-04-04 09:40 UTC, plyhun commented on cms-core/src/main/java/com/gentics/contentnode/factory/object/PageFactory.java
> -					// when the page to move does not have a language, but the target node has languages, we let the page have the first
This part of the code causes the UT to fail, as initially the page being moved does not have a language, and so I have doubts that we need to set those forcefully on a move.

2024-04-04 09:42 UTC, plyhun commented on cms-core/src/main/java/com/gentics/contentnode/publish/mesh/MeshPublisher.java
> +			Map<Integer, Set<String>> deleteOfflineMap = PublishQueue.getObjectIdsWithAttributes(clazz, true, checkedNode, Action.DELETE, Action.OFFLINE);
Here we tell apart the DELETEd and REMOVEd objects just as documented - DELETE means complete removal, REMOVE means the object being moved elsewhere. Forms require this tellapart explicitly.

2024-04-04 09:44 UTC, plyhun commented on pom.xml
> +		<surefire.skip>false</surefire.skip>
I'd like to have an ability to build the whole project, including unit tests, without an actual run of the tests.

2024-04-04 14:45 UTC, npomaroli requested changes

2024-04-04 14:45 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/factory/object/PageFactory.java
> -					// when the page to move does not have a language, but the target node has languages, we let the page have the first
This part must not be removed, it was added on purpose (the reason is in the comment).
But the failing UT shows another problem: When moving a page from Node A to Node B, all language variants of the page must be removed from Mesh (for Node A), not only the language variant, the page currently has. I will provide a fix for this.

2024-04-04 14:45 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/publish/mesh/MeshPublisher.java
> +			Stream.of(deleteOfflineMap.entrySet().stream(), removeMap.entrySet().stream())
Doing it this way moves the check for stopped publish processes out of the loop. This must not be done, because then the publish process cannot be interrupted during removal of objects from mesh.

2024-04-04 14:45 UTC, npomaroli commented on cms-oss-changelog/src/changelog/entries/2024/04/7736.SUP-16409.bugfix
> +When moving an object (Page, File etc) between the nodes, that point to the completely different Mesh CRs, the following publish process may fail with an item duplication error. This has been fixed.
Actually, the problem of duplicate items only arises when objects are moved between nodes, which publish into the same Mesh instance (via the same or different CRs).

2024-04-05 07:23 UTC, plyhun commented on pom.xml
> +		<surefire.skip>false</surefire.skip>
`-DskipTests` skips building test deps, which means that every new build, that depends on those, fails. I need them to be built, but not run.

2024-04-08 08:56 UTC, plyhun commented on pom.xml
> +		<surefire.skip>false</surefire.skip>
> I have verified that this is in fact the case.

It has been never the case. For instance, if building CMS OSS with this flag, the following build of CMS fails on missing parent test-lib, which has not been build, thus - not installed.

2024-04-12 08:16 UTC, merged