GPU-1707: CMS: Automatic Page Translations
gentics/cms-oss pull request #305
Opened 2024-06-10 09:34 UTC by guggi

Issue: https://jira-gentics.atlassian.net/browse/GPU-1707

2024-06-25 09:56 UTC, deckdom requested changes

2024-06-25 09:56 UTC, deckdom commented on cms-ui/apps/editor-ui/src/app/shared/components/translate-page-modal/translate-page-modal.component.ts
> +        this.createTranslationWithFunction(this.folderActions.createPageTranslation)
Bitte keine methode direkt von einem Service/Class als parameter irgendwo rein passen.
Sonst gibt es probleme mit der `this` referenzierung im nachhinein, welche nicht leicht zu finden sind wenn man es nicht weiß.

Das lambda sollte somit nicht auf `createPageTranslation` gesetzt werden, sondern hier in dem aufruf:
```ts
this.createTranslationWithFunction(
    (pageId, options) => this.folderActions.createPageTranslation(pageId, options)
);
```

Das einzige was man sich bei deinem ansatz "spart", ist das man *hier* zwar kein lambda erstellen muss, aber muss dafür an allen anderen punkten das berücksichtigen das es lambdas sein müssen.

2024-06-25 09:56 UTC, deckdom commented on cms-ui/apps/editor-ui/src/app/shared/providers/translation-actions/translation-actions.service.ts
> +    public translatePage = (pageId: number, params?: TranslationRequestParams): Promise<PageResponse> => {
Bitte hier normale funktionen machen wie bei den anderen services:
```
public translatePage(pageId: number, params?: TranslationRequestParams): Promise<PageResponse> {
```

2024-06-25 09:56 UTC, deckdom commented on cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts
> +    createPageTranslation = async(pageId: number, params: TranslationRequestOptions): Promise<PageResponse> => {
Bitte normale funktion draus machen wie beim rest des services:
```
async createPageTranslation(pageId: number, params: TranslationRequestOptions): Promise<PageResponse> {
```

2024-06-25 09:56 UTC, deckdom commented on cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts
> +            const res = await translationRequestFunction.call(this, pageId, {language: languageCode, channelId: nodeId});
Nicht die `call` function benutzen, sondern die `translateRequestFunction` als lambda erwarten:
```
const res = await translateRequestFunction(pageId, {language: languageCode, channelId: nodeId});
```

2024-06-25 12:48 UTC, guggi commented on cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts
> +            const res = await translationRequestFunction.call(this, pageId, {language: languageCode, channelId: nodeId});
d2048398cee2fc7e7519703b6b7e50dd11a4b8c8

2024-06-25 12:48 UTC, guggi commented on cms-ui/apps/editor-ui/src/app/state/providers/folder-actions/folder-actions.service.ts
> +    createPageTranslation = async(pageId: number, params: TranslationRequestOptions): Promise<PageResponse> => {
d2048398cee2fc7e7519703b6b7e50dd11a4b8c8

2024-06-25 12:48 UTC, guggi commented on cms-ui/apps/editor-ui/src/app/shared/providers/translation-actions/translation-actions.service.ts
> +    public translatePage = (pageId: number, params?: TranslationRequestParams): Promise<PageResponse> => {
d2048398cee2fc7e7519703b6b7e50dd11a4b8c8

2024-06-25 12:48 UTC, guggi commented on cms-ui/apps/editor-ui/src/app/shared/components/translate-page-modal/translate-page-modal.component.ts
> +        this.createTranslationWithFunction(this.folderActions.createPageTranslation)
d2048398cee2fc7e7519703b6b7e50dd11a4b8c8

2024-06-27 13:37 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/translation/PageTranslationService.java
> +				// get the language variant (if one already exists)
todo: refactor this also

2024-07-01 08:29 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/etc/Feature.java
> +	TRANSLATION(false);
Should this be per node?

2024-07-01 08:31 UTC, guggi commented on cms-core/src/main/java/com/gentics/contentnode/runtime/ConfigurationValue.java
> +	TRANSLATION_PROVIDER("TRANSLATION_PROVIDER", "com.gentics.contentnode.translation.provider", "translation.provider"),
remove

2024-07-01 14:24 UTC, npomaroli requested changes

2024-07-01 14:24 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/translation/PageTranslationService.java
> +	private void deleteExistingLanguageVariantsWithWastebin(Page page, String languageCode) throws NodeException {
deleteExistingLanguageVariantsFromWastebin

2024-07-01 14:24 UTC, npomaroli commented on cms-ui/apps/editor-ui/src/app/shared/components/translate-page-modal/translate-page-modal.tpl.html
> +    <gtx-button type="primary" (click)="createAutomaticallyTranslatedPage()" [disabled]="(creating$ | async) || !form?.valid">
Only show the button, if the feature is activated for the node

2024-07-09 12:09 UTC, guggi commented on cms-oss-doc/src/main/guides.yml
> +    - title:  "Automatic Page Translation"
is this section the right place?

2024-10-21 11:21 UTC, merged