SUP-15430: Fix spellchecker
gentics/cms-oss pull request #347
Opened 2024-08-12 14:08 UTC by guggi

Issue: https://jira-gentics.atlassian.net/browse/SUP-15430

2024-08-13 08:40 UTC, guggi commented on cms-core/src/main/resources/com/gentics/contentnode/runtime/config.yml
> +  - "gcn/spellcheck"
Maybe remove this to not have it activated as default?

2024-08-20 11:23 UTC, deckdom commented on cms-core/src/main/resources/com/gentics/contentnode/runtime/config.yml
> +  - "gcn/spellcheck"
As far as I can tell, this isn't a special/paid/enterprise feature, and spellchecks are quite common, so having this enabled on default should be fine.

Regarding the change in the Aloha-Editor Repo:
Please add the entry for the `gcnSpellCheck` in here instead (Line `78`):

```yml
      - id: view
        merge:
          components: 'append'
        components:
          - 'gcnSpellCheck'
```

This should simply add the entry to the settings

2024-08-20 11:24 UTC, deckdom requested changes
Please see comment

2024-08-20 11:37 UTC, guggi commented on cms-core/src/main/resources/com/gentics/contentnode/runtime/config.yml
> +  - "gcn/spellcheck"
b57a6e7d

2024-08-20 13:30 UTC, merged