Add support for setting Global ID for Overviews from outside.
gentics/cms-oss pull request #83
Opened 2023-06-30 10:42 UTC by plyhun

This functionality is required for importing.

2023-06-30 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gentics/cms-oss?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gentics/cms-oss?pullRequest=83) before we can accept your contribution.<br/><hr/>**Serhii Plyhun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gentics/cms-oss?pullRequest=83) it.</sub>

2023-07-11 13:20 UTC, npomaroli requested changes

2023-07-11 13:20 UTC, npomaroli commented on cms-core/src/main/java/com/gentics/contentnode/rest/util/ModelBuilder.java
> +		restOverview.setGlobalId(nodeOverview.getGlobalId().toString());
Add null-check for nodeOverview.getGlobalId()

2023-07-11 14:48 UTC, plyhun commented on cms-core/src/main/java/com/gentics/contentnode/rest/util/ModelBuilder.java
>  				Tag tag = null;
This alien set of changes is a consequence of a weird upstream merge. For instance, this change already exists in the target branch:
https://github.com/gentics/cms-oss/blob/hotfix-6.0.x/cms-core/src/main/java/com/gentics/contentnode/rest/util/ModelBuilder.java#L1484

2023-07-12 06:13 UTC, npomaroli commented
Can you please make a clean MR out ot this? Based on hotfix-6.0.x and directed back to hotfix-6.0.x.

2023-07-12 09:04 UTC, plyhun commented
--> https://github.com/gentics/cms-oss/pull/102

2023-07-14 09:36 UTC, closed without merging